[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
bonding_curve = "8mpK8svcXKb4PuY8QtE3xd8k3AcBgonUJBSgMazeo3tz"

[programs.devnet]
bonding_curve = "8mpK8svcXKb4PuY8QtE3xd8k3AcBgonUJBSgMazeo3tz"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "./id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
